spring:
  datasource:
    url: jdbc:mysql://mysql:3306/payment_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${MYSQL_USER:payment_user}
    password: ${MYSQL_PASSWORD:payment_pass}
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

account:
  service:
    url: http://account-service:8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka